config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sing_out: :logout }

  resources :badges, only: %i[index show]

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    resource :gists, only: :create
    
    member do
      get :result      
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end

    resources :gists, only: :index
    resources :badges
  end

end

app/models/badge.rb
class Badge < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_badges

  validates :title, presence: true
  validates :description, presence: true
  validates :rule, presence: true
  validate  :validate_rule_is_available
  validates :image_path, presence: true, format: { with: URI::regexp }

  def self.available_rules
    Specifications::Badges::RULES.keys
  end

  def rule
    attributes['rule']&.to_sym
  end

  private
  
  def validate_rule_is_available
    errors.add(:rule, "is not available") if !rule.in? self.class.available_rules
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[ show edit update destroy ]
  before_action :set_rules, only: %i[ new edit create update ]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to @badge, notice: "Badge was successfully created."
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to @badge, notice: "Badge was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to badges_url, notice: "Badge was successfully destroyed."
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def set_rules
    @rules = BadgeCreationService.rules_collection 
  end

  def badge_params
    BadgeCreationService.badge_params(params)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    if current_user.has_badges?
      @user_badges = current_user.badges
      @badges = Badge.find(Badge.ids - current_user.badge_ids)
    else
      @badges = Badge.all
    end
  end

  def show
    @badge = Badge.find(params[:id])
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def show_user_badges(user_badges)
    if user_badges
      content_tag(:h1, 'Your badges:') +
      (render partial: 'badges/badge', collection: user_badges) +
      content_tag(:h3, 'But you can get more:')
    else
      content_tag(:h1, "You have no badges now. But you can get!")
    end
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.title %></td>
  <td><%= badge.description %></td>
  <td><%= badge.rule %></td>
  <td><%= badge.rule_value %></td>
  <td>
    <img src="<%= badge.image_path %>" width="30", height="30">
    <% # = image_tag source: badge.image_path, size: [30, 30] %>
  </td> 
  <td><%= link_to 'Show', [:admin, badge] %></td>
  <td><%= link_to 'Edit', edit_admin_badge_path(badge) %></td>
  <td><%= link_to 'Destroy', [:admin, badge], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], class: "form-control" do |form| %>
  <%= render 'shared/errors', model_instance: @badge %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title, id: :test_title %>
  </div>


  <%= form.collection_radio_buttons :rule, @rules, :key, :description do |rule| %>
    <div class="field">
      <%= rule.radio_button %>
      <%= rule.label %>

      <% if rule.object.select_arguements.present? %>
        <%= form.collection_select rule.object.key,
                                   *rule.object.select_arguements,
                                   { prompt: true,
                                     selected: @badge.rule == rule.object.key ? @badge.rule_value : nil }, 
                                   { id: "#{rule.object.key}_rule_value" } %>
      <% end %>  
    </div>
  <% end %> 

  <div class="field">
    <%= form.label :image_path %><br />
    <%= form.text_field :image_path, id: :badge_image_path %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/badges/edit.html.erb
<h1>Editing Badge</h1>

<%= render 'form', badge: @badge %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/admin/badges/index.html.erb
<h1>Badges</h1>

<%= link_to 'New Badge', new_admin_badge_path %>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Rule</th>
      <th>Rule value</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @badges %>
  </tbody>
</table>

app/views/admin/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/show.html.erb
<div class="card ml-2 mb-2" style="width: 18rem;">
  <img src="<%= @badge.image_path %>" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= @badge.title %></h5>
    <p class="card-text"><%= @badge.description %></p>
  </div>
</div>
<%= link_to 'Edit', edit_admin_badge_path(@badge) %> |
<%= link_to 'Back', admin_badges_path %>