config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sing_out: :logout }

  resources :badges, only: %i[index show]

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    resource :gists, only: :create
    
    member do
      get :result      
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end

    resources :gists, only: :index
    resources :badges
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  PASSAGE_TRESHOLD = 85

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end
    save!
  end

  def complited?
    current_question.nil?
  end

  def successfully_passed?
    complited? && calculate_result > PASSAGE_TRESHOLD
  end

  def calculate_result
    if self.correct_questions > 0
      self.correct_questions.to_f / self.test.questions.count * 100
    else
      0
    end
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  
  before_action :find_test_passage, only: %i[show update result gist]

  def show
  end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.complited?
      TestsMailer.complited_test(@test_passage).deliver_now
      BadgeManagerService.call(@test_passage)
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def result
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def color_result(test_passage)
    result = test_passage.calculate_result
    if test_passage.successfully_passed?
      content_tag :span, "#{'%.2f' % result}%", style: 'color: green;'
    else
      content_tag :span, "#{'%.2f' % result}%", style: 'color: red;'
    end
  end

  def question_numeration(test_passage)
    current_question_index = test_passage.test.questions.order(:id).index(test_passage.current_question) + 1
    current_question_index = content_tag :span,
                                         current_question_index,
                                         class: "current-progress",
                                         data: { test_passage_id: test_passage.id } 
    questiions_count = content_tag :span,
                                   test_passage.test.questions.count,
                                   class: "full-progress",
                                   data: { test_passage_id: test_passage.id } 
    "(#{current_question_index}/#{questiions_count})".html_safe
  end

  def passage_message(test_passage)
    if test_passage.successfully_passed?
      'Congratulation! You passed this test!'
    else
      'Sorry, test failed. Learn more and try again!'
    end
  end

  def time_limit(test_passage)
    if test_passage.test.with_timer?
      time_left = test_passage.time_left
      content_tag :div, class: "test-timer", data: { test_passage_id: @test_passage.id } do
        hidden_field_tag("time-limit", time_left, class: "time-limit") +
        content_tag(:p, time_left, class: "current-time-limit")
      end
    end
  end
end

app/views/test_passages/result.html.erb
<% if @test_passage.complited? %>
  <h1>Test <%= @test_passage.test.title %> complite!</h1>
  <h3>Your result is <%= color_result(@test_passage) %></h3>
  <h3><%= passage_message(@test_passage) %></h3>
<% else %>
  <h1>Result for test <%= @test_passage.test.title %> is not found, you forget to passed test.</h1>
<% end %>

<%= link_to 'Back to tests', tests_path %>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %></h1>

<%= time_limit(@test_passage) %>

<%= content_tag :div, class: "progress", data: { test_passage_id: @test_passage.id } do %>
  <%= content_tag :div,
                  '',
                  class: "progress-bar bg-success",
                  data: { test_passage_id: @test_passage.id } %>
<% end %>

<b>
  <%= question_numeration(@test_passage) %> Question: <br>
  <b><%= @test_passage.current_question.body %></b>
</b>

<%= form_with url: test_passage_path(@test_passage), class: "timer-form", data: { test_passage_id: @test_passage.id }, local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |block|%>
    <p>
      <%= block.check_box id: "answer_ids_#{block.object.id}" %>
      <%= block.label %>
    </p>
  <% end %>

  <p><%= link_to "Gist Question", test_passage_gists_path(@test_passage), method: :post %></p>
  <p><%= form.submit 'Next'%></p>
<% end %>