config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sing_out: :logout }

  resources :badges, only: %i[index show]

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    resource :gists, only: :create
    
    member do
      get :result      
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end

    resources :gists, only: :index
    resources :badges
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_answer_count, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_answer_count
    errors.add(:question, 'question can contain max 4 answers') if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  
  before_action :find_answer, only: %i[show edit update destroy]
  before_action :find_question, only: %i[new create]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_answer_not_found

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    if @answer.save
      redirect_to [:admin, @answer]
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer]
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to [:admin, @answer.question]
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def rescue_with_answer_not_found
    render plain: "Answer with id = #{params[:id]} not found"
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/views/admin/answers/_answer.html.erb
<li>
<%= answer.body %><br>
<%= link_to 'Show', admin_answer_path(answer) %>
<%= link_to 'Edit', edit_admin_answer_path(answer) %>
<%= link_to 'Delete', 
                admin_answer_path(answer),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', model_instance: @answer %>
  
  <p>
    <%= form.label :body %>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Edit answer</h1>
<h2>For question:</h2>
<h3><%= @answer.question.body %></h3>

<%= render 'form' %>

<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>Create new answer</h1>
<h2>For question:</h2>
<h3><%= @answer.question.body %></h3>

<%= render 'form' %>

<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/admin/answers/show.html.erb
<h2>Answer with id <%= @answer.id%> for question:</h2>
<h3><%= @answer.question.body %></h3>
<p><%= @answer.body %></p>
<p>Correct: <%= @answer.correct %></p>

<%= link_to 'Edit', edit_admin_answer_path(@answer) %>
<%= link_to 'Back', admin_question_path(@answer.question) %>