config/routes.rb
Rails.application.routes.draw do
  
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sing_out: :logout }

  resources :badges, only: %i[index show]

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    resource :gists, only: :create
    
    member do
      get :result      
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end

    resources :gists, only: :index
    resources :badges
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to [:admin, @question]
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to [:admin, @question]
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to [:admin, @question.test]
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: "Question with id = #{params[:id]} not found"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create new question for #{question.test.title}"
    else
      "Edit #{question.test.title} question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', model_instance: @question %>
  
  <%= form.label :body %>
  <%= form.text_field :body, id: :question_body %>

  <%= form.submit %>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to 'Show', admin_question_path(question) %></td>
  <td><%= link_to 'Edit', edit_admin_question_path(question) %></td>
  <td><%= link_to 'Delete', 
                  admin_question_path(question),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/questions/edit.html.erb
<h1><%= question_header(@question) %></h1>

<%= render 'form' %>

<%= link_to 'Back', admin_question_path(@question) %>

app/views/admin/questions/new.html.erb
<h1><%= question_header(@question) %></h1>

<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@question.test) %>

app/views/admin/questions/show.html.erb
<h2>Question with id <%= @question.id%> for test <%= @question.test.title %></h2>
<h3>The question is:</h3>
<p><%= @question.body %></p>
<%= link_to 'Edit', edit_admin_question_path(@question) %>

<h2>Answers</h2>
<%= link_to "Create new answer", new_admin_question_answer_path(@question) %>
<ol>
  <%= render @question.answers %>
</ol>

<%= link_to 'Back', admin_test_path(@question.test) %>